### ISSUE TITLE
麻烦更新下Readme文档，按现有步骤项目没运行起来

### ISSUE THREAD

**Issue by JimmyLee05** [mpflutter/mpflutter_template#1]
1. /.dart pub get 提示找不到
<img width="1359" alt="截屏2021-12-10 下午5 01 11" src="https://user-images.githubusercontent.com/13815229/145547270-07c77b9a-d96b-4294-a1b3-e1d2f937f144.png">

可能是 /.mpdart pub get

后面 /.mpflutter run 运行程序时，没跑起来
<img width="866" alt="截屏2021-12-10 下午5 21 13" src="https://user-images.githubusercontent.com/13815229/145549860-335f8dee-a1f6-45c9-814c-183741734e3a.png">

**Comment by PonyCui** [comment]
https://github.com/mpflutter/mpflutter_template/commit/37ac84e25ccb64f13641fadd722adba5dea018fd
